### ISSUE TITLE
Is it possible to pass 2D numpy arrays as input instead of png/jpg for image classification? 

### ISSUE THREAD

**Issue by Jim2002** [ludwig-ai/ludwig#484] opened 2019-08-10 10:45 UTC
Is it possible to pass 2D numpy arrays as input instead of png/jpg for image classification? 
I have made some 2D numpy arrays (values between 0~1 , black and white, 1 channel) that I would like to train them as images for classification, I was wondering if it's possible to pass the arrays to Ludwig strait away instead of converting all the arrays to png then pass to Ludwig? If yes, how? Thanks for any help.

**Comment by w4nderlust** [comment] 2019-08-10 22:51
Not at the moment. We will likely add a similar option in the future (see other feature requests). For the time being I suggest you to save your numpys and feed the paths where you saved them. You can use a temp dir and delete once done.

**Comment by Jim2002** [comment] 2019-08-11 02:48
> Not at the moment. We will likely add a similar option in the future (see other feature requests). For the time being I suggest you to save your numpys and feed the paths where you saved them. You can use a temp dir and delete once done.

Ok thank you very much.

**Comment by w4nderlust** [comment] 2020-02-18 02:26
This is also a duplicate of https://github.com/uber/ludwig/issues/268 for most intents and purposes.

**Comment by w4nderlust** [comment] 2021-05-23 01:13
It took a while from the original request, but PR #1174 addresses this issue, closing it, please let us know if this works for you @Jim2002 .

**Closed by w4nderlust** 2021-05-23 01:13 UTC
Labels: duplicate, feature request
