### ISSUE TITLE
Flakiness in `test_hyperopt_ray_horovod.py::test_hyperopt_executor`

### ISSUE THREAD

**Issue by geoffreyangus** [ludwig-ai/ludwig#2322] opened 2022-07-28 01:05 UTC
Seeing `tests/integration_tests/test_hyperopt_ray_horovod.py::test_hyperopt_executor[scenario1]` fail intermittently.

Example CI test failure from [this PR](https://github.com/ludwig-ai/ludwig/pull/2310): https://github.com/ludwig-ai/ludwig/runs/7549814691?check_suite_focus=true. Re-running the failed jobs allowed the tests to pass successfully.

**Comment by tgaddair** [comment] 2022-09-12 21:24
Possible duplicate of #2451.

**Comment by arnavgarg1** [comment] 2022-10-12 23:37
Fixed by https://github.com/ludwig-ai/ludwig/pull/2599, closing

**Closed by arnavgarg1** 2022-10-12 23:37 UTC
Labels: bug, productivity and code quality
