### ISSUE TITLE
Ray Import Failed

### ISSUE THREAD

**Issue by MarijnQ** [ludwig-ai/ludwig#2038] opened 2022-05-17 08:39 UTC
**Describe the bug**
I tried to re-use a model that I have used multiple times however, today I get the error that ray cant be imported.
I tried re-running my experiment and I get the same error.
Exact error codes are,
Experiment:
```
!ludwig experiment \
 --dataset CompanyAndIndust.csv\
 --config_file model_definition.yaml

NumExpr defaulting to 2 threads.
import ray failed with exception: No module named 'ray'
usage: ludwig experiment [options]
ludwig experiment: error: one of the arguments -c/--config -cs/--config_str is required
```

Predict:
```
from ludwig.api import LudwigModel
model = LudwigModel.load("/path/")
predictions, _ = model.predict(dft.rename(columns={'company_name': 'name'} ))

Import ray failed with exception: No module named 'ray'
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py:299: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at  ../aten/src/ATen/native/Convolution.cpp:744.)
  self.padding, self.dilation, self.groups)
```

**To Reproduce**

1 installed the tools + libraries
!pip install tensorflow-gpu
!pip install ray
!pip install ludwig

import pandas as pd
from datetime import datetime as dt
import numpy as np
from google.colab import drive
from google.colab import files
drive.mount('drive')

2 I run predict and I get the error

**Environment (please complete the following information):**

- OS: Mac running Python on Google Colab
- Version 12.2,
- Python version 3.7.13
- Ludwig version 0.5

Thank in advance guys

**Comment by aabmets** [comment] 2022-05-17 11:41
1) Have you installed ray with `pip install ray`
2) Are you sure ray is compatible with your OS
3) Are you sure you installed ray into the python venv which you are using?

**Comment by MarijnQ** [comment] 2022-05-19 10:29
> 

Great shout, I have not done that, I assumed it would be installed as I installed Ludwig. After installing it, the issue is still there, unfortunately.
How can I check whether ray in compatible with my OS?

**Comment by MarijnQ** [comment] 2022-05-19 10:30
> 

@tgaddair Thanks for your reply, this was my mistake, I'm sorry, I am currently on 3.7.13 and I will change that in the issue.

**Comment by tgaddair** [comment] 2022-05-19 19:35
Thanks @MarijnQ, looking at your example, it looks like the issue may actually not be related to ray, necessarily. I suspect the model you're trying to load was trained with Ludwig v0.4 and tensorflow, is that right? In Ludwig v0.5, we've updated Ludwig to use PyTorch.

For the `experiment` call, it looks like the issue is that the param `--config_file` was changed to `--config`. Can you try changing that param and try again?

It is curious that you have Ray installed and yet it is complaining about it not being available. I am not immediately sure why that's happening, but I will see if I can repro that specific issue on our side.

**Comment by MarijnQ** [comment] 2022-05-20 07:23
@tgaddair Thanks for the fast reply. The change to` --config` was the fix.
Only problem I have now, the dataset is about 200k rows, that training the model takes 17hours + to train 1 epoch, instead of 20 minutes.
Any advice on how to reduce that?

**Comment by tgaddair** [comment] 2022-05-20 15:15
Glad that worked! I'm guessing the issue you're running into is that your PyTorch version isn't able to use the GPU in your Collab notebook. Can you try running the following to check this?

```
import torch
print(torch.cuda_is_available())
```

If it prints False, you can try re-installing torch with GPU support:

```
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
```

Then restart the notebook and try running the `cuda_is_available()` check again. If it prints True, then you should be able to use the GPU in Ludwig.

**Comment by MarijnQ** [comment] 2022-05-23 13:31
@tgaddair Thanks for the replay again, really appreciate it.
The issue is unfortunately not resolved as I get neither True or False.
I followed your steps and I got error code:
`AttributeError: module 'torch' has no attribute 'cuda_is_available'`

I tried running it on TPU, GPU and on the Google Colab native runtype. But no success on either of these.

**Comment by tgaddair** [comment] 2022-05-23 16:03
No problem, @MarijnQ!

Can you try running `!nvcc --version` to see what version of CUDA is being run in your notebook? That will help us decide which version of PyTorch needs to be installed.

**Comment by aabmets** [comment] 2022-05-24 09:26
@MarijnQ 
Since you're running your code on Google Colab, have you checked if a cloud GPU or TPU has been assigned to your runtime? I can't give the directions from the top of my head, but you should google how to run torch models on Colab cloud GPU-s or TPU-s.

**Comment by MarijnQ** [comment] 2022-05-24 10:32
This is the response @tgaddair ,

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0

**Comment by tgaddair** [comment] 2022-05-26 00:08
Hey @MarijnQ, it looks like your notebook is GPU-capable. Another thing you can check is GPU visibility with `nvidia-smi`.

Apologies, I sent you the wrong torch command earlier. Can you actually run `torch.cuda.is_available()` and share the output?

**Comment by MarijnQ** [comment] 2022-05-27 07:38
@tgaddir

So the response to this is:
`Fri May 27 07:30:31 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
`

and the result from torch.cuda.is_available() is True.

I don't know if there has been another update, but the runtime atm is back to 30/35 mins instead of 1 hour and 17 mins

**Comment by tgaddair** [comment] 2022-05-27 16:23
Hey @MarijnQ, we did release a new version a few days ago that may have helped. Glad to hear the performance is closer to what you were seeing before. It looks like you are able to see the GPU in your notebook and use it effectively. I will go ahead and close this issue for now, happy to reopen if there are more issues that come up.

**Closed by tgaddair** 2022-05-27 16:23 UTC
